#!/usr/bin/env python
# encoding: utf-8
# Copyright (C) 2017 John Törnblom
#
# This file is part of pyxtuml.
#
# pyxtuml is free software: you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later version.
#
# pyxtuml is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with pyxtuml. If not, see <http://www.gnu.org/licenses/>.
import xtuml

from bridgepoint import ooaofooa
from xtuml import relate
from xtuml import where_eq as where


m = ooaofooa.empty_model()

#
# Create top-level package (External Entities - generated by pyxtuml)
#
ep_pkg = m.new('EP_PKG', Name='External Entities - generated by pyxtuml')
pe_pe = m.new('PE_PE', Visibility=True, type=7)
relate(pe_pe, ep_pkg, 8001)

#
# Create an external entity (My_External_Entity)
#
s_ee = m.new('S_EE', Name='My_External_Entity', Key_Lett='My_External_Entity')
pe_pe = m.new('PE_PE', Visibility=True, type=5)
relate(s_ee, pe_pe, 8001)
relate(pe_pe, ep_pkg, 8000)

#
# Create a bridge operation (My_Bridge_Operation: boolean)
#
s_dt = m.select_one('S_DT', where(Name='boolean'))
s_brg = m.new('S_BRG', Name='My_Bridge_Operation')
relate(s_brg, s_ee, 19)
relate(s_brg, s_dt, 20)

#
# Create a bridge parameter (My_Parameter: string)
#
s_dt = m.select_one('S_DT', where(Name='string'))
s_bparm = m.new('S_BPARM', Name='My_Parameter')
relate(s_bparm, s_brg, 21)
relate(s_bparm, s_dt, 22)


print('-- root-types-contained: Package_c')
print('-- generics')
print('-- BP 7.1 content: StreamData syschar: 3 persistence-version: 7.1.6')
print(xtuml.serialize_instances(m))
print('')
print('')
print('-- Copy the SQL statements above, and paste them into the BridgePoint editor')
print('-- with a project selected in the project explorer. NOTE: do not remove the')
print('-- first few comments.')
